name: Deploy AKS, Key Vault, and Arc
on:
    workflow_dispatch:
        inputs:
          clusterResourceGroup:
            description: 'The resource group where to create the Arc-enabled cluster.'
            required: true
            type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Parse AZURE_CREDENTIALS
      id: parse_creds
      run: |
        echo "${{ secrets.AZURE_CREDENTIALS }}" > creds.json
        clientId=$(jq -r .clientId creds.json)
        clientSecret=$(jq -r .clientSecret creds.json)
        subscriptionId=$(jq -r .subscriptionId creds.json)
        echo "CLIENT_ID=$clientId" >> $GITHUB_ENV
        echo "CLIENT_SECRET=$clientSecret" >> $GITHUB_ENV
        echo "SUBSCRIPTION_ID=$subscriptionId" >> $GITHUB_ENV

     # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ env.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ github.event.inputs.clusterResourceGroup }}
        template: ./infra/AKS/aks.bicep
        parameters: servicePrincipalClientId=${{ env.CLIENT_ID }} servicePrincipalClientSecret=${{ env.CLIENT_SECRET }}
        failOnStdErr: false