name: Deploy AKS, Key Vault, Log Analytics
on:
    workflow_dispatch:
        inputs:
          clusterSubscription:
            description: 'The subscription ID where to create the Arc-enabled cluster.'
            required: true
            type: string
            default: '5f5dd16b-0879-4c86-884f-30347411b95f'
          clusterResourceGroup:
            description: 'The resource group where to create the Arc-enabled cluster.'
            required: true
            type: string
            default: 'arctest001'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Checkout repository
      uses: actions/checkout@v2

    # Deploy kevault 
    - name: deploy kevault
      id: deploy_key_vault
      uses: azure/arm-deploy@v1
      with:
       subscriptionId: ${{ github.event.inputs.clusterSubscription }}
       resourceGroupName: ${{ github.event.inputs.clusterResourceGroup }}
       template: ./infra/AKS/kevault.bicep
       parameters: servicePrincipalClientId=${{ secrets.CLIENT_ID }} servicePrincipalClientSecret=${{ secrets.CLIENT_SECRET }} sshPublicKey="${{ secrets.RSA_PUBLIC_KEY }}"
       failOnStdErr: false
    
    # Deploy log analytics
    - name: deploy log analytics
      id: deploy_log_analytics
      uses: azure/arm-deploy@v1
      with:
         subscriptionId: ${{ github.event.inputs.clusterSubscription }}
         resourceGroupName: ${{ github.event.inputs.clusterResourceGroup }}
         template: ./infra/AKS/loganalytics.bicep
         failOnStdErr: false    

    # Deploy AKS
    - name: deploy AKS
      id: deploy_aks
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ github.event.inputs.clusterSubscription }}
        resourceGroupName: ${{ github.event.inputs.clusterResourceGroup }}
        template: ./infra/AKS/aks.bicep
        parameters: servicePrincipalClientId=${{ secrets.CLIENT_ID }} servicePrincipalClientSecret=${{ secrets.CLIENT_SECRET }} logAnalyticsWorkspaceResourceID=${{ steps.deploy_log_analytics.outputs.logAnalyticsWorkspaceId }} sshRSAPublicKey="${{ secrets.RSA_PUBLIC_KEY }}"
        failOnStdErr: false