name: Deploy Arc
on:
    workflow_dispatch:
        inputs:
          clusterSubscription:
            description: 'The subscription ID where the Arc-enabled cluster is.'
            required: true
            type: string
            default: '5f5dd16b-0879-4c86-884f-30347411b95f'
          clusterResourceGroup:
            description: 'The resource group where the Arc-enabled cluster is.'
            required: true
            type: string
            default: 'arctest001'
          clusterName:
              description: 'The Arc-enabled cluster name.'
              required: true
              type: string
              default: 'arctest001aks'
          KeyVaultName:
              description: 'The KeyVault name.'
              required: true
              type: string
              default: 'arctest001kv'
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Checkout repository
      uses: actions/checkout@v2

    # Deploy arc
    - name: deploy arc
      id: deploy_arc
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ github.event.inputs.clusterSubscription }}
        resourceGroupName: ${{ github.event.inputs.clusterResourceGroup }}
        template: ./infra/AKS/arc.bicep
        parameters: clusterName=${{ github.event.inputs.clusterName }} sshRSAPublicKey="${{ secrets.RSA_PUBLIC_KEY }}"
        failOnStdErr: false

    # Deploy AIO via cli
    - name: Deploy AIO to Arc-enabled Cluster
      id: deploy_aio_cli
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az iot ops init \
              --cluster ${{ github.event.inputs.clusterName }} \ 
              --resource-group ${{ github.event.inputs.clusterResourceGroup }} \ 
              --kv-id ${{ github.event.inputs.keyVaultName }} \
              --sp-app-id ${{ secrets.CLIENT_ID }}  \
              --sp-secret ${{ secrets.CLIENT_SECRET }} \
              --kv-sat-secret-name servicePrincipalClientSecret
              --no-deploy